using FluentNHibernate.Mapping;
using Psps.Models.Domain;
using System;
using System.Collections.Generic;
using System.Text;

namespace Psps.Data.Mappings
{
    public partial class PspDocViewMap : BaseEntityMap<PspDocView, int>
    {
        protected override void MapId()
        {
            Id(x => x.PspMasterId).GeneratedBy.Identity().Column("PspMasterId");
        }

        protected override void MapEntity()
        {
            Map(x => x.DocumentDate).Column("DocumentDate");
            Map(x => x.ThreeWeekAfterDocumentDate).Column("ThreeWeekAfterDocumentDate").Not.Nullable();
            Map(x => x.PspMasterId).Column("PspMasterId").Not.Nullable().Precision(10);
            Map(x => x.PreviousPspMasterId).Column("PreviousPspMasterId").Precision(10);
            Map(x => x.OrgId).Column("OrgId").Precision(10);
            Map(x => x.EngOrgName).Column("EngOrgName").Not.Nullable().Length(256);
            Map(x => x.ChiOrgName).Column("ChiOrgName").Not.Nullable().Length(100);
            Map(x => x.EngRegisteredAddress1).Column("EngRegisteredAddress1");
            Map(x => x.EngRegisteredAddress2).Column("EngRegisteredAddress2");
            Map(x => x.EngRegisteredAddress3).Column("EngRegisteredAddress3");
            Map(x => x.EngRegisteredAddress4).Column("EngRegisteredAddress4");
            Map(x => x.EngRegisteredAddress5).Column("EngRegisteredAddress5");
            Map(x => x.EngRegisteredAddressFull).Column("EngRegisteredAddressFull");
            Map(x => x.ChiRegisteredAddress1).Column("ChiRegisteredAddress1");
            Map(x => x.ChiRegisteredAddress2).Column("ChiRegisteredAddress2");
            Map(x => x.ChiRegisteredAddress3).Column("ChiRegisteredAddress3");
            Map(x => x.ChiRegisteredAddress4).Column("ChiRegisteredAddress4");
            Map(x => x.ChiRegisteredAddress5).Column("ChiRegisteredAddress5");
            Map(x => x.ChiRegisteredAddressFull).Column("ChiRegisteredAddressFull");
            Map(x => x.EngMailingAddress1).Column("EngMailingAddress1").Length(400);
            Map(x => x.EngMailingAddress2).Column("EngMailingAddress2").Length(400);
            Map(x => x.EngMailingAddress3).Column("EngMailingAddress3").Length(400);
            Map(x => x.EngMailingAddress4).Column("EngMailingAddress4").Length(400);
            Map(x => x.EngMailingAddress5).Column("EngMailingAddress5").Length(400);
            Map(x => x.EngMailingAddressFull).Column("EngMailingAddressFull");
            Map(x => x.ChiMailingAddress1).Column("ChiMailingAddress1").Length(100);
            Map(x => x.ChiMailingAddress2).Column("ChiMailingAddress2").Length(100);
            Map(x => x.ChiMailingAddress3).Column("ChiMailingAddress3").Length(100);
            Map(x => x.ChiMailingAddress4).Column("ChiMailingAddress4").Length(100);
            Map(x => x.ChiMailingAddress5).Column("ChiMailingAddress5").Length(100);
            Map(x => x.ChiMailingAddressFull).Column("ChiMailingAddressFull");
            Map(x => x.TelNum).Column("TelNum").Length(50);
            Map(x => x.URL).Column("URL").Length(256);
            Map(x => x.ApplicantFirstName).Column("ApplicantFirstName").Length(100);
            Map(x => x.ApplicantLastName).Column("ApplicantLastName").Length(50);
            Map(x => x.ApplicantEngSalute).Column("ApplicantEngSalute").Length(200);
            Map(x => x.ApplicantChiLastName).Column("ApplicantChiLastName").Length(10);
            Map(x => x.ApplicantChiFirstName).Column("ApplicantChiFirstName").Length(5);
            Map(x => x.ApplicantChiSalute).Column("ApplicantChiSalute").Length(200);
            Map(x => x.ApplicantPosition).Column("ApplicantPosition").Length(100);
            Map(x => x.PspRef).Column("PspRef").Length(10);
            Map(x => x.PermitNum).Column("PermitNum").Length(200);
            Map(x => x.PreviousPspRef).Column("PreviousPspRef").Length(10);
            Map(x => x.PreviousPermitNum).Column("PreviousPermitNum").Length(200);
            Map(x => x.PreviousPermitIssueDate).Column("PreviousPermitIssueDate");
            Map(x => x.PreviousPermitNumList).Column("PreviousPermitNumList");
            Map(x => x.ContactPersonFirstName).Column("ContactPersonFirstName").Length(100);
            Map(x => x.ContactPersonLastName).Column("ContactPersonLastName").Length(50);
            Map(x => x.EngSalute).Column("EngSalute").Length(200);
            Map(x => x.ContactPersonChiFirstName).Column("ContactPersonChiFirstName").Length(5);
            Map(x => x.ContactPersonChiLastName).Column("ContactPersonChiLastName").Length(10);
            Map(x => x.ChiSalute).Column("ChiSalute").Length(200);
            Map(x => x.ContactPersonPosition).Column("ContactPersonPosition").Length(100);
            Map(x => x.ContactPersonTelNum).Column("ContactPersonTelNum").Length(50);
            Map(x => x.ContactPersonFaxNum).Column("ContactPersonFaxNum").Length(50);
            Map(x => x.ContactPersonEmailAddress).Column("ContactPersonEmailAddress").Length(100);
            Map(x => x.NewApplicantIndicator).Column("NewApplicantIndicator");
            Map(x => x.EngProcessingOfficerPost).Column("EngProcessingOfficerPost").Length(73);
            Map(x => x.ChiProcessingOfficerPost).Column("ChiProcessingOfficerPost").Length(73);
            Map(x => x.PspYear).Column("PspYear").Length(5);
            Map(x => x.FirstEventDate).Column("FirstEventDate");
            Map(x => x.LastEventDate).Column("LastEventDate");
            Map(x => x.PendingFirstEventDate).Column("PendingFirstEventDate");
            Map(x => x.PendingLastEventDate).Column("PendingLastEventDate");
            Map(x => x.EventPeriodFrom).Column("EventPeriodFrom");
            Map(x => x.EventPeriodTo).Column("EventPeriodTo");
            Map(x => x.PreviousEventPeriodFrom).Column("PreviousEventPeriodFrom");
            Map(x => x.PreviousEventPeriodTo).Column("PreviousEventPeriodTo");
            Map(x => x.BypassValidationIndicator).Column("BypassValidationIndicator");
            Map(x => x.ApplicationReceiveDate).Column("ApplicationReceiveDate");
            Map(x => x.ApplicationCompletionDate).Column("ApplicationCompletionDate");
            Map(x => x.ActionBuDate).Column("ActionBuDate");
            Map(x => x.DisasterMasterId).Column("DisasterMasterId").Precision(10);
            Map(x => x.BeneficiaryOrg).Column("BeneficiaryOrg").Length(500);
            Map(x => x.EngFundRaisingPurpose).Column("EngFundRaisingPurpose").Length(4000);
            Map(x => x.ChiFundRaisingPurpose).Column("ChiFundRaisingPurpose").Length(4000);
            Map(x => x.EventTitle).Column("EventTitle").Length(2000);
            Map(x => x.EngCharitySalesItem).Column("EngCharitySalesItem").Not.Nullable().Length(2000);
            Map(x => x.ChiCharitySalesItem).Column("ChiCharitySalesItem").Not.Nullable().Length(2000);
            Map(x => x.EngUsedLanguage).Column("EngUsedLanguage").Length(200);
            Map(x => x.ChiUsedLanguage).Column("ChiUsedLanguage").Length(200);
            Map(x => x.ApplicationDisposalDate).Column("ApplicationDisposalDate");
            Map(x => x.EngApplicationResult).Column("EngApplicationResult").Length(200);
            Map(x => x.ChiApplicationResult).Column("ChiApplicationResult").Length(200);
            Map(x => x.EngRejectReason).Column("EngRejectReason").Length(200);
            Map(x => x.ChiRejectReason).Column("ChiRejectReason").Length(200);
            Map(x => x.OtherRejectReason).Column("OtherRejectReason").Length(256);
            Map(x => x.EngPspNotRequireReason).Column("EngPspNotRequireReason").Length(200);
            Map(x => x.ChiPspNotRequireReason).Column("ChiPspNotRequireReason").Length(200);
            Map(x => x.OtherPspNotRequireReason).Column("OtherPspNotRequireReason").Length(256);
            Map(x => x.EngCaseCloseReason).Column("EngCaseCloseReason").Length(200);
            Map(x => x.ChiCaseCloseReason).Column("ChiCaseCloseReason").Length(200);
            Map(x => x.OtherCaseCloseReason).Column("OtherCaseCloseReason").Length(256);
            Map(x => x.PermitRevokeIndicator).Column("PermitRevokeIndicator");
            Map(x => x.EngSpecialRemark).Column("EngSpecialRemark");
            Map(x => x.ChiSpecialRemark).Column("ChiSpecialRemark");
            Map(x => x.OtherSpecialRemark).Column("OtherSpecialRemark").Length(4000);
            Map(x => x.TrackRecordStartDate).Column("TrackRecordStartDate");
            Map(x => x.TrackRecordEndDate).Column("TrackRecordEndDate");
            Map(x => x.TrackRecordDetails).Column("TrackRecordDetails").Length(4000);
            Map(x => x.AfsRecordStartDate).Column("AfsRecordStartDate");
            Map(x => x.AfsRecordEndDate).Column("AfsRecordEndDate");
            Map(x => x.AfsRecordDetails).Column("AfsRecordDetails").Length(4000);
            Map(x => x.FundUsed).Column("FundUsed").Length(200);
            Map(x => x.EngDocSubmission).Column("EngDocSubmission");
            Map(x => x.ChiDocSubmission).Column("ChiDocSubmission");
            Map(x => x.SubmissionDueDate).Column("SubmissionDueDate");
            Map(x => x.FirstReminderIssueDate).Column("FirstReminderIssueDate");
            Map(x => x.FirstReminderDeadline).Column("FirstReminderDeadline");
            Map(x => x.SecondReminderIssueDate).Column("SecondReminderIssueDate");
            Map(x => x.SecondReminderDeadline).Column("SecondReminderDeadline");
            Map(x => x.AuditedReportReceivedDate).Column("AuditedReportReceivedDate").Length(100);
            Map(x => x.PublicationReceivedDate).Column("PublicationReceivedDate").Length(100);
            Map(x => x.OfficialReceiptReceivedDate).Column("OfficialReceiptReceivedDate").Length(100);
            Map(x => x.NewspaperCuttingReceivedDate).Column("NewspaperCuttingReceivedDate").Length(100);
            Map(x => x.DocReceivedRemark).Column("DocReceivedRemark").Length(4000);
            Map(x => x.GrossProceed).Column("GrossProceed").Precision(12).Scale(2);
            Map(x => x.Expenditure).Column("Expenditure").Precision(12).Scale(2);
            Map(x => x.NetProceed).Column("NetProceed").Precision(12).Scale(2);
            Map(x => x.OrgAnnualIncome).Column("OrgAnnualIncome").Precision(12).Scale(2);
            Map(x => x.SanctionListIndicator).Column("SanctionListIndicator");
            Map(x => x.QualifyOpinionIndicator).Column("QualifyOpinionIndicator");
            Map(x => x.QualityOpinionDetail).Column("QualityOpinionDetail").Length(4000);
            Map(x => x.WithholdingListIndicator).Column("WithholdingListIndicator");
            Map(x => x.ArCheckIndicator).Column("ArCheckIndicator");
            Map(x => x.PublicationCheckIndicator).Column("PublicationCheckIndicator");
            Map(x => x.OfficialReceiptCheckIndicator).Column("OfficialReceiptCheckIndicator");
            Map(x => x.NewspaperCheckIndicator).Column("NewspaperCheckIndicator");
            Map(x => x.DocRemark).Column("DocRemark").Length(4000);
            Map(x => x.PermitIssueDate).Column("PermitIssueDate");
            Map(x => x.EngSFCName).Column("EngSFCName");
            Map(x => x.ChiSFCName).Column("ChiSFCName");
            Map(x => x.SFCTel).Column("SFCTel");
            Map(x => x.SFCEmail).Column("SFCEmail");
            Map(x => x.EngEOIILF5Name).Column("EngEOIILF5Name");
            Map(x => x.ChiEOIILF5Name).Column("ChiEOIILF5Name");
            Map(x => x.EOIILF5Tel).Column("EOIILF5Tel");
            Map(x => x.EOIILF5Email).Column("EOIILF5Email");
            Map(x => x.DDAFormIndicator).Column("IsSsaf");
        }
    }
}